---
- hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: chrisnt5/hello-go:1.0.2

  pre_tasks:
  tasks:
  # Build the hello-go Docker image
    - name: Get existing image hash.
      shell: |
        nerdctl images -q {{ image_name }}
      register: image_hash
      changed_when: false
    - name: Build image if it's not already built.
      shell: |
        nerdctl build -t {{ image_name }} ../hello-go
      when: not image_hash.stdout
      

